### ISSUE TITLE
`node add`  and `node set` have confusing parameters for network device

### ISSUE THREAD

**Issue by kivel** [hpcng/warewulf#259]
The CLI arguments for `wwctl node add` and `wwctl node set` are confusing for network devices.

`wwctl node add` uses `-N` for the device.
However, `wwctl node set` uses `-N` for the name.

This causes a rather peculiar, and I assume unintended, behavior.
```
wwctl node add -v foo -N eth0

wwctl node set foo -N eth0 -H aa:bb:cc:dd:ee:11

cat /usr/local/etc/warewulf/nodes.conf 

nodeprofiles:
  default:
    comment: This profile is automatically included for each node
nodes:
  foo:
    profiles:
    - default
    network devices:
      default:
        type: ""
        onboot: true
        device: eth0
        hwaddr: ""
        ipaddr: ""
        netmask: ""
        gateway: ""
        default: false
      eth0:
        type: ""
        onboot: true
        device: eth0
        hwaddr: aa:bb:cc:dd:ee:11
        ipaddr: ""
        netmask: ""
        gateway: ""
        default: false
```
