### ISSUE TITLE
RFE 4.4: Drop concept of `default` or `primary` network device, add concept of `network`.

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#451]
Tagging @jcsiadal as this is my attempt to write down things we've previously talked about around this topic and this is related to https://github.com/hpcng/warewulf/issues/391.

The use of `default` for a network device is confusing. Even more so in that we have the redundant (for any multihomed node) `--netdev` and `--netname` which ultimately refer to the same thing. The RFE is

Add a section to nodes.conf for `networks`, example layout is: 

```
networks:
  provisioning:
    type: ethernet
    gateway: 192.168.0.1
    netmask: 255.255.255.0
    broadcast: 192.168.0.255
    tags:
     # maybe should be a first class citizen, but I needed a tags example
      mtu: 9000 
    dns:
      nameservers:
        - 192.168.0.1
        - 192.168.0.2
      search domains:
        - cluster.local
    dhcp:
      enabled: true
      dynamic range: 192.168.0.[129-191]
  ib:
    type: infiniband
    gateway: 192.168.1.1
    netmask: 255.255.255.0
    broadcast: 192.168.1.255
    dns:
      nameservers:
        - 192.168.1.1
        - 192.168.1.2
      search domains:
        - cluster.ib
    dhcp:
      enabled: false
...
```

With this addition:
* `--netdev` can now always refer to the device name
* `--network` for a `--netdev` can assign a device to a network using an unambiguous term.
* `--netname`, `--netmask`, `--primary` and `--gateway` can be removed from the network device data structure and `wwctl node set` command. 
* `dhcpd` config can be specified per-network. 
* The `dhcp` section of `warewulf.conf` can be reduced to just information about what service to use for DHCP (`warewulfd`, `dhcpd`, `dnsmasq`, ...), details specific to chosen service and a global `enabled` flag.

This simplifies network device handling and things previously determined by `--primary` or `default` can move into network device tags, e.g., to pick which interface to use for DNS resolving a network tag for `PEERDNS=[yes|no]` could be used in the template for setting up the network device configs and these values supplied by DHCP or branched on this tag in the ifcfg template if static addressing is used.

**Comment by anderbubble** [comment]
I discovered this had 4.4 in the title, so I've added it to the milestone for now.

**Comment by blixuga** [comment]
I'd like to throw my 2cents in as well, and express my support of this change.  I agree that the "default" item is confusing for me as well.  Here are a few reasons it would be better served to have networks as an object type vs a property of a node:

Our current provisioning system is handling more than one cluster, some of which have different "default" network configurations, including type.  I cannot have a "default" network, but I can have a cluster "default".

We have a single-source-of-truth we want to import compute node information from, in which "network/interface" is a separate object from the device.  There is currently no provision for us to create a "default" interface on the server, but we easily can tag an interface as the "default" one.

This would also lend itself to trimming down the size of the nodes.yaml file.

As a side suggestion as well, adding a `domainname` option on the network could help facilitate fqdn's going forward.

**Comment by mslacken** [comment]
A node would always need a primary/default network as this is network which used for provisioning and so identifying the node. At the moment the primary interface is configured per node and this would be consistent with an introduction of networks,

**Comment by griznog** [comment]
@blixuga you can sort of fake this by using `--netname=NETWORKNAME` for your interfaces. That at least collects all adapters in a given network under something that can be searched for easily.  My nodes look like this in `nodes.conf`

```
  cpu-a-1:
    cluster name: bruno
    ipmi:
      write: "false"
    profiles:
    - role-compute
    - site-tags-bruno
    network devices:
      clusternet:
        onboot: "true"
        device: enp161s0f1np1
        hwaddr: b8:ce:f6:a1:69:b7
        ipaddr: 100.64.2.1
        primary: "true"
      infiniband:
        onboot: "true"
        device: ib0
        hwaddr: b8:ce:f6:a1:69:b6
        ipaddr: 100.64.18.1
        primary: "false"
        tags:
          ibclientid: ff:00:00:00:00:00:02:00:00:02:c9:00:b8:ce:f6:03:00:a1:69:b6
          ibhwaddr: 00:00:10:49:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:a1:69:b6
          ibportguid: b8:ce:f6:03:00:a1:69:b6
```
I've tried a couple of approaches to manage networks via profiles, but the merging of profiles (last one wins) makes that impossible (or at least too difficult) to do.  

There's also still an issue with the `default` device coming back during some `wwctl` operations on node/profile configs if you don't have one, so I wind up running `wwctl node set --netdel default "*"` occasionally to clean that up.
