### ISSUE TITLE
RFE: Specify general network configs in a common block in `nodes.conf` rather than per-node.

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#636]
Feature requested is to break out some network config, basically options which tend to be global for that network, into their own section in `nodes.conf`. For example a clusters networks might look like:

```
networks:
  clusternet:
      type: Ethernet
      network: 100.64.0.0/20
      gateway: 100.64.15.254
      dns:
          domain: clusternet
          nameservers:
              - 100.64.15.254
              - 100.64.15.253
          search:
              - exampledom.com
      options:
          mtu: 1500
          vlan: 1
  infiniband:
      type: Infiniband
      network: 172.16.0.0/24
      gateway: 172.16.0.254
      dns:
          domain: ib
          nameservers:
              - 172.16.0.254
              - 172.16.0.253
  management:
      type: Ethernet
      network: 100.64.32.0/20
      gateway: 100.64.47.254
      dns:
          domain: management
          nameservers:
              - 100.64.31.254
              - 100.64.31.253
      options:
          mtu: 1500
          vlan: 2
```

These common blocks can then be used by `wwctl` when configuring the master node and eliminate a lot of boilerplate config in the `nodes` section. Instead of this:

```
  gpu-sm02-18:
    network devices:
      eno1:
        type: Ethernet
        onboot: "true"
        device: eno1
        hwaddr: 3c:ec:ef:d2:b9:02
        ipaddr: 100.64.1.68
        netmask: 255.255.240.0
        gateway: 100.64.15.254
        primary: "true"
      ib0:
        type: Infiniband
        onboot: "true"
        device: ib0
        hwaddr: 3c:ec:ef:37:25:f4
        ipaddr: 172.16.0.218
        netmask: 255.255.255.0
        gateway: 172.16.0.254
        primary: "true"
```

The config would be reduced to just node/device specific items or things that override the network config:
```
  gpu-sm02-18:
    network devices:
      eno1:
        network: clusternet
        onboot: "true"
        device: eno1
        hwaddr: 3c:ec:ef:d2:b9:02
        ipaddr: 100.64.1.68
        primary: "true"
      ib0:
        network: infiniband
        onboot: "true"
        device: ib0
        hwaddr: 3c:ec:ef:37:25:f4
        ipaddr: 172.16.0.218
        primary: "true"
```

Eliminating the repeated boilerplate in the node configs reduces the typo error surface when working with network settings. 

Parallel to this it would be nice to un-obfuscate the meanings of `--netname` and `--netdev`, either letting `--netname` point at the network the device is part of or dropping it entirely and replacing with `--network`.
