### ISSUE TITLE
Default interface returns primary=true even when set to false/no

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#657]
### Version of Warewulf

What version of Warewulf are you using? Run

```
wwctl version:	 4.4.0-1.git_88b740d
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_88b740d"
```

### Expected behavior

When I create a node and set its default interface to not be primary, I expect it to not show as primary in node list and template variables.

### Actual behavior

It appears that the primary boolean always returns True.

### Steps to reproduce this behavior

`nodes.conf`:

```yaml
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
nodes:
  n3:
    profiles:
    - default
    network devices:
      default:
        ipaddr: 192.168.200.102
        primary: "no"
```

```shell
# wwctl node list -a n3 | grep primary
n3                   default:primary    --           true
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### How did you install Warewulf

Built from source using mock.

```
make dist
tar -xf warewulf-4.4.0.tar.gz warewulf-4.4.0/warewulf.spec
mock --rebuild --spec=warewulf-4.4.0/warewulf.spec --sources=. --resultdir=.
```
