### ISSUE TITLE
Unable to boot node. TFTP open timeout

### ISSUE THREAD

**Issue by edvinas31** [hpcng/warewulf#684]
### Version of Warewulf

What version of Warewulf are you using? Run

`wwctl version`

### Expected behavior

Node booted successfully

### Actual behavior

What actually happened? Why was it incorrect?

Getting error:

`"PXE-E32: TFTP open timeout"`
Also it seems to me when I start tftp service is active and running for approximately 15 minutes, but after compute node shows TFTP error then tftp service becomes dead:
```
[rocky@IBM3 log]$ sudo systemctl status tftp
● tftp.service - Tftp Server
   Loaded: loaded (/usr/lib/systemd/system/tftp.service; indirect; vendor preset: disabled)
   Active: inactive (dead) since Mon 2023-02-13 15:58:56 UTC; 21min ago
     Docs: man:in.tftpd
  Process: 18129 ExecStart=/usr/sbin/in.tftpd -s /var/lib/tftpboot (code=exited, status=0/SUCCESS)
 Main PID: 18129 (code=exited, status=0/SUCCESS)

Feb 13 15:43:55 IBM3 systemd[1]: Started Tftp Server.
Feb 13 15:58:56 IBM3 systemd[1]: tftp.service: Succeeded.
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release

NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

### How did you install Warewulf

I did install warewulf using this quickstart guide:
https://warewulf.org/docs/development/quickstart/el8.html

**Comment by anderbubble** [comment]
> it seems to me when I start tftp service is active and running for approximately 15 minutes, but after compute node shows TFTP error then tftp service becomes dead

The tftp service is started reactively using tftp.socket. Before systemd, a similar thing happened with xinetd.

> PXE-E32: TFTP open timeout

Do you have firewalld or another firewall configuration active? If you're using firewalld, you likely need to allow access to tftp.

Something like

```
firewall-cmd --add-service tftp --permanent && firewall-cmd --reload
```

**Comment by edvinas31** [comment]
Thanks for fast response. I already added tftp service before together with other services like it was shown in EL8 Quickstart guide https://warewulf.org/docs/development/quickstart/el8.html:

```
[rocky@IBM3 log]$ sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources:
  services: cockpit dhcpv6-client nfs ssh tftp warewulf
  ports:
  protocols:
  forward: no
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

```
