### ISSUE TITLE
merge overlays from multiple profiles

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#885]
Right now, overlay lists from multiple profiles override each other entirely. So in this configuration:

```
nodeprofiles:
  profile1:
    runtime overlay:
    - overlay1
    - overlay2
  profile2:
    runtime overlay:
    - overlay2
    - overlay3

nodes:
  node1:
    profiles:
    - profile1
    - profile2
```

`node1` ultimately gets overlays `overlay2,overlay3` because the entirety of the runtime overlay specification from profile2 overrides profile1.

There should be a mechanism for allowing overlays from multiple profiles to be included in a final node. For example, perhaps in the above situation the node should have overlays 1, 2, and 3. Or perhaps there should be a syntax like

```
  profile2:
    runtime overlay:
    - +overlay2
    - +overlay3
```

to add overlays, and

```
  profile2:
    runtime overlay:
    - -overlay2
    - -overlay3
```

to remove overlays.

**Comment by griznog** [comment]
Overlays (also described in https://github.com/hpcng/warewulf/issues/652):

 - Merge the overlay list from the node and any profiles included in the node.
 - For any overlay in that list which matches `/^!(.*)$`, remove it and any entries for the given overlay without the `!`.
 - Make the resulting list both unique and sorted alphanumerically. 

Network Devices:
( Disclaimer: The network config parts of warewulf need a re-design/re-write, see https://github.com/hpcng/warewulf/issues/451 )

- Pull in network devices from node config.
- Get list of profiles assigned to the node.
- Sort the profile list alphanumerically.
- For each profile, for each network device, **if and only if** the node config defines a network device of the same name, merge any values  and tags found in the profile **that are missing** from the node config for that network device. 

The behavior there is that the last profile to write a value wins, but a profile never overrides a node supplied value nor does it create a network device that wasn't explicitly included in the node config. 

Kernel Args:

Kernel args should also be a list and follow similar semantics as described above for overlays, allowing multiple profiles to build kernel args and include the `!` operator to allow the node config to exclude args supplied by profiles.

**Comment by griznog** [comment]
This python code expresses my previous comment including handling nested profiles:

```python
#!/usr/bin/env python3

import yaml, re, pdb

def get_nested_profiles(profile, profiles):
    try:
        for p in profilesdb[profile]['profiles']:
            if p not in profiles:
                profiles.append(p)
                profiles = get_nested_profiles(p, profiles)
    except:
        pass

    return profiles

re_not_overlay = re.compile('^!(.+)$')

with open('nodes.conf') as f:
    node_conf = yaml.load(f, Loader=yaml.SafeLoader)

nodesdb = node_conf['nodes']
profilesdb = node_conf['nodeprofiles']

for node in nodesdb.keys():
    # Start with node-specific overlays, if they exist.
    try:
        runtime = nodesdb[node]['runtime overlay']
    except:
        runtime = []

    # Get profiles used by this node
    try: 
        profiles = nodesdb[node]['profiles']
        for profile in nodesdb[node]['profiles']:
            profiles = get_nested_profiles(profile, profiles)
    except:
        profiles = []

    # Add overlays from profiles.
    for profile in profiles:
        try:
            runtime.extend(profilesdb[profile]['runtime overlay'])
        except:
            # Profile has no overlays
            continue
    
    # Make list unique.
    runtime = list(set(runtime))

    # Remove explicitly excluded overlays.
    excludes = []
    includes = []
    for overlay in runtime:
        if overlay.startswith('!'):
            excludes.append(overlay[1:])
        else:
            includes.append(overlay)

    # Make these unique, sort includes.
    excludes = list(set(excludes))
    includes = sorted(list(set(includes)))

    # Build final list.
    runtime = []
    for overlay in includes:
        if overlay not in excludes:
            runtime.append(overlay)

    print("%s: %s" % ( node, ','.join(runtime) ))
```

This sample nodes.conf is based on a story I wish was true and while a bit contrived, expresses some sort of realistic examples of how profile nesting and proper merging of keys expands what is possible with profiles.

```yaml

nodeprofiles:
  cluster-base:
    runtime overlay:
      - slurm
      - munge
      - autofs
      - authconfig
  cluster-gpu:
    profiles:
      - cluster-base
    runtime overlay:
      - gpu-setup
  cluster-login:
    profiles:
      - cluster-base
    runtime overlay:
    - fail2ban
    - firewalld
    - '!slurm'
    - '!munge'
  cluster-storage-jbod:
    profiles:
      - cluster-base
    runtime overlay:
    - storage-setup
    - znapzend
    - zfs
    - multipath
    - '!slurm'
    - '!munge'

nodes:
  cpu-1:
    profiles:
    - cluster-base
  gpu-1: 
    profiles:
    - cluster-gpu
  login-external:
    profiles:
      - cluster-login
  login-internal:
    profiles:
      - cluster-login
    runtime overlay:
      - '!fail2ban'
  storage-jbod:
    profiles:
      - cluster-storage-jbod
  storage-plain:
    profiles:
      - cluster-storage-jbod
    runtime overlay:
      - '!multipath'
```
